# Generated by Django 3.1 on 2020-09-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursery',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='book_images/'),
        ),
    ]
